### ISSUE TITLE
Maybe a bug.

### ISSUE THREAD

**Issue by floudk** [tonghuikang/lux-ai-2021#3]
https://github.com/tonghuikang/lux-ai-2021/blob/86d06bb0ae799bd66f732052597fd67d2d91cbf0/lux/game.py#L447

When reading your sharing code for lux-ai-2021, I found there may be a bug.

In file `game.py` , the function `calculate_distance_matrix()` near line 447, I think it should be:
```python
x_distance_from_edge = min(x, self.map_width-x-1)
```
Since we are calculating the distance from edge here, that's to say we need y-to-edge and x-to-edge.

Maybe I am wrong and not get the key point.  
And thanks for your sharing : )

**Comment by tonghuikang** [comment]
Hi there

Yup, it is distance from corner rather than distance from edge.

I think I tried distance from edge but it seems that distance from corner will give a better signal. Distance from corner is opposite of distance from center, which is my intention.

Thanks for reading, probably it helps you have an idea how the logic can be structured.

**Comment by floudk** [comment]
I see !
Again, thanks for your responding and sharing code !
